include:
# Lily58 without dongle 不带dongle的Lily58
  # Lily58 with oled display(with nice_oled module) 适用于带oled的Lily58
  - board: nice_nano_v2 
    shield: Lily58_left nice_oled
    snippet: studio-rpc-usb-uart 
    artifact-name: Lily58_left_oled
  - board: nice_nano_v2
    shield: Lily58_right nice_oled
    artifact-name: Lily58_right_oled
  # Lily58 with nice!view display(with nice_view_custom module) 适用于带nice_view的Lily58
  - board: nice_nano_v2
    shield: Lily58_left Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Lily58_left_nice_view
  - board: nice_nano_v2
    shield: Lily58_right Nice_view_config nice_view_custom
    artifact-name: Lily58_right_nice_view


#Lily58 with dongle 带dongle的Lily58
  # dongle with LCD display 带LCD显示的dongle
  - board: nice_nano_v2
    shield: Lily58_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Lily58_central_dongle
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Lily58_dongle_left nice_oled
    artifact-name: Lily58_peripheral_left_oled
  - board: nice_nano_v2
    shield: Lily58_dongle_right nice_oled
    artifact-name: Lily58_peripheral_right_oled   
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Lily58_dongle_left Nice_view_config nice_view_custom
    artifact-name: Lily58_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Lily58_dongle_right Nice_view_config nice_view_custom
    artifact-name: Lily58_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset
