include:
# Helix without dongle 不带dongle的Helix
  # Helix with oled display(with nice_oled module) 适用于带oled的Helix
  - board: nice_nano_v2 
    shield: Helix_left nice_oled
    snippet: studio-rpc-usb-uart 
    artifact-name: Helix_left_oled
  - board: nice_nano_v2
    shield: Helix_right nice_oled
    artifact-name: Helix_right_oled
  # Helix with nice!view display(with nice_view_custom module) 适用于带nice_view的Helix
  - board: nice_nano_v2
    shield: Helix_left Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Helix_left_nice_view
  - board: nice_nano_v2
    shield: Helix_right Nice_view_config nice_view_custom
    artifact-name: Helix_right_nice_view


#Helix with dongle 带dongle的Helix
  # dongle with LCD display 带LCD显示的dongle
  - board: nice_nano_v2
    shield: Helix_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Helix_central_dongle
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Helix_dongle_left nice_oled
    artifact-name: Helix_peripheral_left_oled
  - board: nice_nano_v2
    shield: Helix_dongle_right nice_oled
    artifact-name: Helix_peripheral_right_oled   
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Helix_dongle_left Nice_view_config nice_view_custom
    artifact-name: Helix_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Helix_dongle_right Nice_view_config nice_view_custom
    artifact-name: Helix_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset