include:
# Corne without dongle 不带dongle的Corne
  # Corne with oled display(with nice_oled module) 适用于带oled的Corne
  - board: nice_nano_v2 
    shield: Corne_left nice_oled
    snippet: studio-rpc-usb-uart 
    artifact-name: Corne_left_oled
  - board: nice_nano_v2
    shield: Corne_right nice_oled
    artifact-name: Corne_right_oled
  # Corne with nice!view display(with nice_view_custom module) 适用于带nice_view的Corne
  - board: nice_nano_v2
    shield: Corne_left Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Corne_left_nice_view
  - board: nice_nano_v2
    shield: Corne_right Nice_view_config nice_view_custom
    artifact-name: Corne_right_nice_view


#Corne with dongle 带dongle的Corne
  # dongle with LCD display 带LCD显示的dongle
  - board: nice_nano_v2
    shield: Corne_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Corne_central_dongle
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Corne_dongle_left nice_oled
    artifact-name: Corne_peripheral_left_oled
  - board: nice_nano_v2
    shield: Corne_dongle_right nice_oled
    artifact-name: Corne_peripheral_right_oled   
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Corne_dongle_left Nice_view_config nice_view_custom
    artifact-name: Corne_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Corne_dongle_right Nice_view_config nice_view_custom
    artifact-name: Corne_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset